#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "lib/lib.h"

static void build_method_attrs_string (char *o, size_t osz, unsigned int flags) {
	/* System.Reflection.MethodAttributes subset */
	const unsigned int MemberAccessMask = 0x0007;
	const unsigned int MdPrivate = 0x0001;
	const unsigned int MdFamANDAssem = 0x0002; /* private protected */
	const unsigned int MdAssembly = 0x0003;    /* internal */
	const unsigned int MdFamily = 0x0004;      /* protected */
	const unsigned int MdFamORAssem = 0x0005;  /* protected internal */
	const unsigned int MdPublic = 0x0006;
	const unsigned int MdStatic = 0x0010;
	const unsigned int MdFinal = 0x0020;
	const unsigned int MdVirtual = 0x0040;
	const unsigned int MdAbstract = 0x0400;
	const char *vis = "";
	switch (flags & MemberAccessMask) {
	case MdPublic: vis = "public"; break;
	case MdFamily: vis = "protected"; break;
	case MdAssembly: vis = "internal"; break;
	case MdFamORAssem: vis = "protected internal"; break;
	case MdFamANDAssem: vis = "private protected"; break;
	case MdPrivate: vis = "private"; break;
	default: vis = ""; break;
	}
	char tmp[128]; tmp[0] = 0;
	if (*vis) {
		strncat (tmp, vis, sizeof (tmp) - 1);
	}
	if (flags & MdStatic) {
		if (*tmp) strncat (tmp, " ", sizeof (tmp) - 1);
		strncat (tmp, "static", sizeof (tmp) - 1);
	}
	if (flags & MdAbstract) {
		if (*tmp) strncat (tmp, " ", sizeof (tmp) - 1);
		strncat (tmp, "abstract", sizeof (tmp) - 1);
	}
	if (flags & MdVirtual) {
		if (*tmp) strncat (tmp, " ", sizeof (tmp) - 1);
		strncat (tmp, "virtual", sizeof (tmp) - 1);
	}
	if (flags & MdFinal) {
		if (*tmp) strncat (tmp, " ", sizeof (tmp) - 1);
		strncat (tmp, "final", sizeof (tmp) - 1);
	}
	if (!*tmp) {
		strncpy (o, "", osz);
	} else {
		strncpy (o, tmp, osz);
		o[osz? osz - 1: 0] = 0;
	}
}

static void print_usage (const char *prog_name) {
	fprintf (stderr, "Usage: %s [-j] [-q] [-l N] [-f] [-a 0xADDR] [-c N] [-v] <executable> <path/to/global-metadata.dat>\n", prog_name);
}

int main (int argc, char *argv[]) {
	bool json_one_line = false;
	bool quiet = false;
	bool debug = false;
	long limit = -1;
	ut64 gmp_addr = 0;
	size_t gmp_count = 0;
	bool fast = false;
	int opt;
	while ((opt = getopt (argc, argv, "jqfvl:a:c:")) != -1) {
		switch (opt) {
		case 'j': json_one_line = true; break;
		case 'q': quiet = true; break;
		case 'f': fast = true; break;
		case 'v': debug = true; break;
		case 'l': limit = strtol (optarg, NULL, 0); break;
		case 'a': gmp_addr = (ut64) strtoull (optarg, NULL, 0); break;
		case 'c': gmp_count = (size_t) strtoull (optarg, NULL, 0); break;
		default:
			print_usage (argv[0]);
			return 1;
		}
	}
	if (argc - optind != 2) {
		print_usage (argv[0]);
		return 1;
	}

	const char *exe_path = argv[optind];
	const char *metadata_path = argv[optind + 1];

	RBuffer *buf = r_buf_new_file (metadata_path, O_RDONLY, 0);
	if (!buf) {
		perror ("Error opening file");
		return 1;
	}

	/* configure debug */
	r2unity_set_debug (debug);
	R2UnityMetadata *meta = r2unity_parse_metadata (buf);
	if (!meta) {
		fprintf (stderr, "Failed to parse metadata\n");
		r_unref (buf);
		return 1;
	}

	size_t type_count = 0;
	Il2CppTypeDefinition *types = r2unity_get_type_definitions (meta, &type_count);

	size_t method_count = 0;
	Il2CppMethodDefinition *methods = r2unity_get_method_definitions (meta, &method_count);

	ut64 *method_ptrs = NULL;
	bool has_ptrs = false;
	if (gmp_addr) {
		has_ptrs = r2unity_read_method_pointers_at (meta, exe_path, gmp_addr, gmp_count, &method_ptrs);
	} else if (fast) {
		/* Auto-detect file type by magic */
		unsigned char magic[4] = {0};
		FILE *fp = fopen (exe_path, "rb");
		if (fp) {
			(void)fread (magic, 1, 4, fp);
			fclose (fp);
		}
		ut32 m = (ut32)magic[0] | ((ut32)magic[1] << 8) | ((ut32)magic[2] << 16) | ((ut32)magic[3] << 24);
		if (magic[0] == 0x7f && magic[1] == 'E' && magic[2] == 'L' && magic[3] == 'F') {
			has_ptrs = r2unity_find_method_pointers_elf (meta, exe_path, &method_ptrs);
		} else if (m == 0xfeedfacf || m == 0xcffaedfe || m == 0xcafebabe || m == 0xbebafeca) {
			has_ptrs = r2unity_find_method_pointers_macho (meta, exe_path, &method_ptrs);
		} else {
			has_ptrs = false;
		}
	} else {
		has_ptrs = false;
	}
	// Recompute has_ptrs by checking any non-zero entry
	if (method_ptrs) {
		for (size_t k = 0; k < method_count; k++) {
			if (method_ptrs[k]) { has_ptrs = true; break; }
		}
	}

	if (json_one_line) {
		// Output a single stable JSON line
		printf ("{\"ok\":true,\"version\":%d,\"types\":%u,\"methods\":%u,\"has_ptrs\":%s}\n",
			meta->version, (unsigned)type_count, (unsigned)method_count, has_ptrs? "true": "false");
		R_FREE (method_ptrs);
		R_FREE (methods);
		R_FREE (types);
		r2unity_free_metadata (meta);
		r_unref (buf);
		return 0;
	}

	if (!quiet) {
		printf ("# r2 script generated by r2unity\n");
		printf ("# Input file: %s\n\n", metadata_path);
	}

	long printed = 0;
	// Keep 1:1 mapping between method index and pointer index.
	// Do NOT shift, gaps (zeros) are expected for abstract/generic/external methods.
	size_t mp_shift = 0;
	// Optionally enrich names with image/module prefix
	size_t img_count = 0;
	Il2CppImageDefinition *images = NULL;
	int *type2img = NULL;
	images = r2unity_get_images (meta, &img_count);
	if (images && type_count > 0) {
		type2img = R_NEWS (int, type_count);
		for (size_t ti = 0; ti < type_count; ti++) type2img[ti] = -1;
		for (size_t ii = 0; ii < img_count; ii++) {
			int start = images[ii].typeStart;
			int count = (int) images[ii].typeCount;
			if (start >= 0 && count > 0) {
				for (int k = 0; k < count && (size_t)(start + k) < type_count; k++) {
					type2img[start + k] = (int) ii;
				}
			}
		}
	}

	// Print methods first, then types, to ensure RVAs are shown in limited output
	if (methods && types && (limit < 0 || printed < limit)) {
		for (size_t j = 0; j < method_count; j++) {
			Il2CppMethodDefinition *m = &methods[j];
			const Il2CppTypeDefinition *td = NULL;
			if (m->declaringType >= 0 && (size_t) m->declaringType < type_count) {
				td = &types[m->declaringType];
			}
			char *ns = td ? (char *) r2unity_get_string (meta, td->namespaceIndex) : NULL;
			char *tn = td ? (char *) r2unity_get_string (meta, td->nameIndex) : NULL;
			char *mn = (char *) r2unity_get_string (meta, m->nameIndex);
			if (mn) {
				char fullname[1024];
				fullname[0] = 0;
				if (ns && *ns) {
					snprintf (fullname, sizeof (fullname), "%s.%s.%s(%u)", ns, tn ? tn : "", mn, (unsigned) m->parameterCount);
				} else if (tn && *tn) {
					snprintf (fullname, sizeof (fullname), "%s.%s(%u)", tn, mn, (unsigned) m->parameterCount);
				} else {
					snprintf (fullname, sizeof (fullname), "%s(%u)", mn, (unsigned) m->parameterCount);
				}
				ut64 addr = 0;
				if (has_ptrs && method_ptrs) {
					size_t idx = j + mp_shift;
					if (idx < method_count) {
						addr = method_ptrs[idx];
					}
				}
					if (limit < 0 || printed < limit) {
						if (addr > 0x1000) {
							r_name_filter (fullname, -1);
							if (type2img && td) {
								int ii = type2img[m->declaringType];
								if (ii >= 0 && (size_t)ii < img_count) {
									char *im = (char *) r2unity_get_string (meta, images[ii].nameIndex);
									if (im && *im) {
									printf ("'@0x%"PFMT64x"'f sym.unity.%s.%s\n", addr, im, fullname);
									char attrs[128]; attrs[0] = 0; build_method_attrs_string (attrs, sizeof (attrs), m->flags);
									if (*attrs) {
										printf ("'@0x%"PFMT64x"'CCu Method: [%s] %s %s\n", addr, im, attrs, fullname);
									} else {
										printf ("'@0x%"PFMT64x"'CCu Method: [%s] %s\n", addr, im, fullname);
									}
										free (im);
									} else {
									printf ("'@0x%"PFMT64x"'f sym.unity.%s\n", addr, fullname);
									char attrs2[128]; attrs2[0] = 0; build_method_attrs_string (attrs2, sizeof (attrs2), m->flags);
									if (*attrs2) {
										printf ("'@0x%"PFMT64x"'CCu Method: %s %s\n", addr, attrs2, fullname);
									} else {
										printf ("'@0x%"PFMT64x"'CCu Method: %s\n", addr, fullname);
									}
									}
								} else {
									printf ("'@0x%"PFMT64x"'f sym.unity.%s\n", addr, fullname);
									char attrs3[128]; attrs3[0] = 0; build_method_attrs_string (attrs3, sizeof (attrs3), m->flags);
									if (*attrs3) {
										printf ("'@0x%"PFMT64x"'CCu Method: %s\n", addr, attrs3);
									}
								}
							} else {
							printf ("# %s\n", fullname);
						}
						printed++;
					}
			}
			free (ns);
			free (tn);
			free (mn);
			if (limit >= 0 && printed >= limit) {
				break;
			}
			}
		}
	}

	if (types && (limit < 0 || printed < limit)) {
		for (size_t j = 0; j < type_count; j++) {
			char *type_name = (char *) r2unity_get_string (meta, types[j].nameIndex);
			char *namespace_name = (char *) r2unity_get_string (meta, types[j].namespaceIndex);
			if (type_name) {
					if (limit < 0 || printed < limit) {
						printed++;
					}
			}
			free (type_name);
			free (namespace_name);
			if (limit >= 0 && printed >= limit) {
				break;
			}
		}
	}

	R_FREE (method_ptrs);
	R_FREE (methods);
	R_FREE (types);
	R_FREE (images);
	R_FREE (type2img);

	r2unity_free_metadata (meta);
	r_unref (buf);

	return 0;
}
