#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib/lib.h"

static void print_usage (const char *prog_name) {
	fprintf (stderr, "Usage: %s [--json-one-line] [--quiet] [-l N] [--fast] [--gmp-addr 0xADDR] [--gmp-count N] <executable> <path/to/global-metadata.dat>\n", prog_name);
}

int main (int argc, char *argv[]) {
	bool json_one_line = false;
	bool quiet = false;
	long limit = -1;
	ut64 gmp_addr = 0;
	size_t gmp_count = 0;
	bool fast = false;
	int i = 1;
	for (; i < argc; i++) {
		if (!strcmp (argv[i], "--json-one-line")) {
			json_one_line = true;
			continue;
		}
		if (!strcmp (argv[i], "--quiet")) {
			quiet = true;
			continue;
		}
		if (!strcmp (argv[i], "--fast")) {
			fast = true;
			continue;
		}
		if (!strcmp (argv[i], "-l") && i + 1 < argc) {
			limit = strtol (argv[++i], NULL, 0);
			continue;
		}
		if (!strcmp (argv[i], "--gmp-addr") && i + 1 < argc) {
			gmp_addr = (ut64) strtoull (argv[++i], NULL, 0);
			continue;
		}
		if (!strcmp (argv[i], "--gmp-count") && i + 1 < argc) {
			gmp_count = (size_t) strtoull (argv[++i], NULL, 0);
			continue;
		}
		break;
	}
	if (argc - i != 2) {
		print_usage (argv[0]);
		return 1;
	}

	const char *exe_path = argv[i];
	const char *metadata_path = argv[i + 1];

	RBuffer *buf = r_buf_new_file (metadata_path, O_RDONLY, 0);
	if (!buf) {
		perror ("Error opening file");
		return 1;
	}

	R2UnityMetadata *meta = r2unity_parse_metadata (buf);
	if (!meta) {
		fprintf (stderr, "Failed to parse metadata\n");
		r_buf_free (buf);
		return 1;
	}

	size_t type_count = 0;
	Il2CppTypeDefinition *types = r2unity_get_type_definitions (meta, &type_count);

	size_t method_count = 0;
	Il2CppMethodDefinition *methods = r2unity_get_method_definitions (meta, &method_count);

	ut64 *method_ptrs = NULL;
	bool has_ptrs = false;
	if (gmp_addr) {
		has_ptrs = r2unity_read_method_pointers_at (meta, exe_path, gmp_addr, gmp_count, &method_ptrs);
	} else if (fast) {
		/* Auto-detect file type by magic */
		unsigned char magic[4] = {0};
		FILE *fp = fopen (exe_path, "rb");
		if (fp) {
			(void)fread (magic, 1, 4, fp);
			fclose (fp);
		}
		ut32 m = (ut32)magic[0] | ((ut32)magic[1] << 8) | ((ut32)magic[2] << 16) | ((ut32)magic[3] << 24);
		if (magic[0] == 0x7f && magic[1] == 'E' && magic[2] == 'L' && magic[3] == 'F') {
			has_ptrs = r2unity_find_method_pointers_elf (meta, exe_path, &method_ptrs);
		} else if (m == 0xfeedfacf || m == 0xcffaedfe || m == 0xcafebabe || m == 0xbebafeca) {
			has_ptrs = r2unity_find_method_pointers_macho (meta, exe_path, &method_ptrs);
		} else {
			/* Fallback to r2-based */
			has_ptrs = r2unity_find_method_pointers (meta, exe_path, &method_ptrs);
		}
	} else {
		has_ptrs = r2unity_find_method_pointers (meta, exe_path, &method_ptrs);
	}
	// Recompute has_ptrs by checking any non-zero entry
	if (method_ptrs) {
		for (size_t k = 0; k < method_count; k++) {
			if (method_ptrs[k]) { has_ptrs = true; break; }
		}
	}

	if (json_one_line) {
		// Output a single stable JSON line
		printf ("{\"ok\":true,\"version\":%d,\"types\":%u,\"methods\":%u,\"has_ptrs\":%s}\n",
			meta->version, (unsigned)type_count, (unsigned)method_count, has_ptrs? "true": "false");
		goto beach;
	}

	if (!quiet) {
		printf ("# r2 script generated by r2unity\n");
		printf ("# Input file: %s\n\n", metadata_path);
	}

	long printed = 0;
	// If we have pointers but leading entries are zero, shift to the first non-zero
	size_t mp_shift = 0;
	if (has_ptrs && method_ptrs) {
		for (size_t k = 0; k < method_count; k++) {
			if (method_ptrs[k] != 0) { mp_shift = k; break; }
		}
	}
	// Print methods first, then types, to ensure RVAs are shown in limited output
	if (methods && types && (limit < 0 || printed < limit)) {
		for (size_t j = 0; j < method_count; j++) {
			Il2CppMethodDefinition *m = &methods[j];
			const Il2CppTypeDefinition *td = NULL;
			if (m->declaringType >= 0 && (size_t) m->declaringType < type_count) {
				td = &types[m->declaringType];
			}
			char *ns = td ? (char *) r2unity_get_string (meta, td->namespaceIndex) : NULL;
			char *tn = td ? (char *) r2unity_get_string (meta, td->nameIndex) : NULL;
			char *mn = (char *) r2unity_get_string (meta, m->nameIndex);
			if (mn) {
				char fullname[1024];
				fullname[0] = 0;
				if (ns && *ns) {
					snprintf (fullname, sizeof (fullname), "%s.%s.%s(%u)", ns, tn ? tn : "", mn, (unsigned) m->parameterCount);
				} else if (tn && *tn) {
					snprintf (fullname, sizeof (fullname), "%s.%s(%u)", tn, mn, (unsigned) m->parameterCount);
				} else {
					snprintf (fullname, sizeof (fullname), "%s(%u)", mn, (unsigned) m->parameterCount);
				}
				ut64 addr = 0;
				if (has_ptrs && method_ptrs) {
					size_t idx = j;
					if (mp_shift) {
						idx = (j + mp_shift) % (method_count? method_count: 1);
					}
					addr = method_ptrs[idx];
				}
				if (limit < 0 || printed < limit) {
#if 0
					printf ("f %s @ 0x%"PFMT64x"\n", fullname, addr);
					printf ("CCu Method: %s @ 0x%"PFMT64x"\n", fullname, addr);
#else
					if (addr > 0x1000) {
						r_name_filter (fullname, -1);
						printf ("'@0x%"PFMT64x"'f sym.unity.%s\n", addr, fullname);
						printf ("'@0x%"PFMT64x"'CCu Method: %s\n", addr, fullname);
					} else {
						printf ("# %s\n", fullname);
					}
#endif
					printed++;
				}
			}
			free (ns);
			free (tn);
			free (mn);
			if (limit >= 0 && printed >= limit) {
				break;
			}
		}
	}

	if (types && (limit < 0 || printed < limit)) {
		for (size_t j = 0; j < type_count; j++) {
			char *type_name = (char *) r2unity_get_string (meta, types[j].nameIndex);
			char *namespace_name = (char *) r2unity_get_string (meta, types[j].namespaceIndex);
			if (type_name) {
				if (limit < 0 || printed < limit) {
#if 0
					if (R_STR_ISNOTEMPTY (namespace_name)) {
						printf ("f %s.%s @ 0x0\n", namespace_name, type_name);
					} else {
						printf ("f %s @ 0x0\n", type_name);
					}
#else
#endif
					printed++;
				}
			}
			free (type_name);
			free (namespace_name);
			if (limit >= 0 && printed >= limit) {
				break;
			}
		}
	}

beach:
	R_FREE (method_ptrs);
	R_FREE (methods);
	R_FREE (types);

	r2unity_free_metadata (meta);
	r_buf_free (buf);

	return 0;
}
