#include <stdio.h>
#include <stdlib.h>
#include "lib/lib.h"

void print_usage(const char *prog_name) {
    fprintf(stderr, "Usage: %s <executable> <path/to/global-metadata.dat>\n", prog_name);
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        print_usage(argv[0]);
        return 1;
    }

    const char *exe_path = argv[1];
    const char *metadata_path = argv[2];

    RBuffer *buf = r_buf_new_file (metadata_path, O_RDONLY, 0);
    if (!buf) {
        perror("Error opening file");
        return 1;
    }

    printf("# r2 script generated by r2unity\n");
    printf("# Input file: %s\n\n", metadata_path);

    R2UnityMetadata *meta = r2unity_parse_metadata (buf);
    if (!meta) {
        fprintf(stderr, "Failed to parse metadata\n");
        r_buf_free (buf);
        return 1;
    }

    size_t type_count;
    Il2CppTypeDefinition *types = r2unity_get_type_definitions (meta, &type_count);
    if (types) {
        for (size_t i = 0; i < type_count; i++) {
            const char *type_name = r2unity_get_string (meta, types[i].nameIndex);
            const char *namespace_name = r2unity_get_string (meta, types[i].namespaceIndex);
            if (type_name) {
                printf("f %s.%s @ 0x0\n", namespace_name ? namespace_name : "", type_name);
            }
        }
        R_FREE (types);
    }

    size_t method_count;
    Il2CppMethodDefinition *methods = r2unity_get_method_definitions (meta, &method_count);
    if (methods) {
        for (size_t i = 0; i < method_count; i++) {
            const char *method_name = r2unity_get_string (meta, methods[i].nameIndex);
            if (method_name) {
                printf("f %s @ 0x0\n", method_name);
                printf("CCu Method: %s @ 0x0\n", method_name);
            }
        }
        R_FREE (methods);
    }

    r2unity_free_metadata (meta);
    r_buf_free (buf);

    return 0;
}
